from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

db = SQLAlchemy()

class User(UserMixin, db.Model):
    """User accounts"""
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    is_admin = db.Column(db.Boolean, default=False)
    is_active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    last_login = db.Column(db.DateTime)
    bet_tracker_starting_bankroll = db.Column(db.Float, default=0.0)  # Bet Tracker feature
    
    # Relationships
    meetings = db.relationship('Meeting', backref='user', lazy=True, cascade='all, delete-orphan')
    
    def set_password(self, password):
        """Hash and set password"""
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        """Check if password matches"""
        return check_password_hash(self.password_hash, password)
    
    def __repr__(self):
        return f'<User {self.username}>'


class Meeting(db.Model):
    """Racing meetings uploaded by users"""
    __tablename__ = 'meetings'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    meeting_name = db.Column(db.String(200), nullable=False)
    track = db.Column(db.String(100))
    date = db.Column(db.Date)
    csv_data = db.Column(db.Text)  # Store original CSV
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    puntingform_id = db.Column(db.String(255))  # PuntingForm API meeting ID
    auto_imported = db.Column(db.Boolean, default=False)  # True if imported from API
    rail_position = db.Column(db.Integer, default=0)   # 0=True, 1-15 = metres out
    pace_bias = db.Column(db.Integer, default=0)        # -2 to +2 (neg=backmarkers, pos=leaders)
    
    # Relationships
    races = db.relationship('Race', backref='meeting', lazy=True, cascade='all, delete-orphan')
    
    def __repr__(self):
        return f'<Meeting {self.meeting_name}>'


class Race(db.Model):
    """Individual races within a meeting"""
    __tablename__ = 'races'
    
    id = db.Column(db.Integer, primary_key=True)
    meeting_id = db.Column(db.Integer, db.ForeignKey('meetings.id'), nullable=False, index=True)
    race_number = db.Column(db.Integer, nullable=False)
    distance = db.Column(db.String(50))
    race_class = db.Column(db.String(50))
    track_condition = db.Column(db.String(50))
    
    # NEW: PuntingForm V2 API data (richer than CSV)
    speed_maps_json = db.Column(db.JSON, nullable=True)
    ratings_json = db.Column(db.JSON, nullable=True)
    sectionals_json = db.Column(db.JSON, nullable=True)
    
    horses = db.relationship('Horse', backref='race', lazy=True, cascade='all, delete-orphan')
    
    def __repr__(self):
        return f'<Race {self.meeting_id}-{self.race_number}>'


class Horse(db.Model):
    """Horses in each race with all their data"""
    __tablename__ = 'horses'
    
    id = db.Column(db.Integer, primary_key=True)
    race_id = db.Column(db.Integer, db.ForeignKey('races.id'), nullable=False, index=True)
    horse_name = db.Column(db.String(100), nullable=False)
    barrier = db.Column(db.Integer)
    weight = db.Column(db.Float)
    jockey = db.Column(db.String(100))
    trainer = db.Column(db.String(100))
    form = db.Column(db.String(50))
    
    # Store all CSV data as JSON for flexibility
    csv_data = db.Column(db.JSON)
    is_scratched = db.Column(db.Boolean, default=False)  # NEW LINE
    
    # Relationships
    prediction = db.relationship('Prediction', backref='horse', uselist=False, cascade='all, delete-orphan')
    
    def __repr__(self):
        return f'<Horse {self.horse_name}>'


class Prediction(db.Model):
    """Predictions/scores generated by your algorithm"""
    __tablename__ = 'predictions'
    
    id = db.Column(db.Integer, primary_key=True)
    horse_id = db.Column(db.Integer, db.ForeignKey('horses.id'), nullable=False, index=True)
    score = db.Column(db.Float, nullable=False)
    predicted_odds = db.Column(db.String(20))
    win_probability = db.Column(db.String(20))
    performance_component = db.Column(db.String(20))
    base_probability = db.Column(db.String(20))
    notes = db.Column(db.Text)
    calculated_at = db.Column(db.DateTime, default=datetime.utcnow)
    best_bet_flagged_at = db.Column(db.DateTime, nullable=True)  # NEW: Track when this appeared on Best Bets
    ml_score = db.Column(db.Float, nullable=True)
    # Snapshot of the live, pre-race Ladbrokes badges shown on Best Bets.  The
    # bit mask is 1=sweet spot, 2=full consensus and 4=20+ ML gap.
    ladbrokes_signal_mask = db.Column(db.Integer, nullable=False, default=0)
    ladbrokes_signal_price = db.Column(db.Float, nullable=True)
    ladbrokes_signals_captured_at = db.Column(db.DateTime, nullable=True)
    # ML Value Edge tracking: captured once, pre-race, the first time this horse's
    # model-vs-market edge cleared VALUE_EDGE_MIN_THRESHOLD_PCT (app.py). Never
    # overwritten afterwards, so this is an honest pre-race snapshot rather than
    # something reconstructed from the closing price/result.
    value_edge_pct = db.Column(db.Float, nullable=True)
    value_edge_ml_win_prob_pct = db.Column(db.Float, nullable=True)
    value_edge_price = db.Column(db.Float, nullable=True)
    value_edge_captured_at = db.Column(db.DateTime, nullable=True)

    def __repr__(self):
        return f'<Prediction {self.horse_id}: {self.score}>'
        
class Result(db.Model):
    """Actual race results for tracking model performance
    
    finish_position codes:
    - 1, 2, 3, 4 = actual finishing positions
    - 5 = unplaced (ran but finished 5th or worse)
    - 0 = scratched (did not run)
    """
    __tablename__ = 'results'
    
    id = db.Column(db.Integer, primary_key=True)
    horse_id = db.Column(db.Integer, db.ForeignKey('horses.id'), nullable=False, index=True)
    finish_position = db.Column(db.Integer, nullable=False)  # 0=scratched, 1-4=placed, 5=unplaced
    sp = db.Column(db.Float, nullable=True)  # NULL for scratched horses
    recorded_at = db.Column(db.DateTime, default=datetime.utcnow)
    recorded_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    # Relationships
    horse = db.relationship('Horse', backref=db.backref('result', uselist=False, cascade='all, delete-orphan'))
    user = db.relationship('User', backref='recorded_results')
    
    @property
    def is_scratched(self):
        """Check if this horse was scratched"""
        return self.finish_position == 0
    
    @property
    def actually_ran(self):
        """Check if this horse actually competed"""
        return self.finish_position > 0
    
    def __repr__(self):
        if self.finish_position == 0:
            return f'<Result {self.horse_id}: SCRATCHED>'
        return f'<Result {self.horse_id}: P{self.finish_position} @ ${self.sp}>'


class Component(db.Model):
    """Betting components with performance tracking for Best Bets feature"""
    __tablename__ = 'components'
    
    id = db.Column(db.Integer, primary_key=True)
    component_name = db.Column(db.String(200), unique=True, nullable=False)
    component_key = db.Column(db.String(120), index=True)  # Stable matching key for Best Bets
    is_active = db.Column(db.Boolean, default=True)  # Show on Best Bets page
    min_roi = db.Column(db.Float, default=10.0)  # Minimum ROI threshold
    min_appearances = db.Column(db.Integer, default=10)  # Minimum sample size
    
    # Display stats (manually updated by you from Data page)
    appearances = db.Column(db.Integer, default=0)
    wins = db.Column(db.Integer, default=0)
    strike_rate = db.Column(db.Float, default=0.0)
    roi_percentage = db.Column(db.Float, default=0.0)
    
    notes = db.Column(db.Text)  # Optional notes about this component
    last_updated = db.Column(db.DateTime, default=datetime.utcnow)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f'<Component {self.component_name}: {self.roi_percentage}% ROI>'
    
    @property
    def display_label(self):
        """Formatted label for display"""
        if self.appearances > 0:
            return f"{self.component_name} ({self.strike_rate:.1f}% SR, {self.roi_percentage:+.1f}% ROI, N={self.appearances})"
        return self.component_name


class StrikeRate(db.Model):
    """PuntingForm trainer/jockey strike-rate snapshots."""
    __tablename__ = 'strike_rates'

    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(20), nullable=False, index=True)
    jurisdiction = db.Column(db.Integer, nullable=False, default=2, index=True)
    entity_id = db.Column(db.String(64), nullable=True, index=True)
    normalised_name = db.Column(db.String(255), nullable=False, index=True)
    name = db.Column(db.String(255), nullable=False)
    start_date = db.Column(db.String(50))
    l100_wins = db.Column(db.Integer, default=0)
    l100_runs = db.Column(db.Integer, default=0)
    career_wins = db.Column(db.Integer, default=0)
    career_runs = db.Column(db.Integer, default=0)
    career_expected_wins = db.Column(db.Float)
    l100_expected_wins = db.Column(db.Float)
    career_actual_to_expected = db.Column(db.Float)
    last100_actual_to_expected = db.Column(db.Float)
    raw_csv_row = db.Column(db.JSON)
    raw_data = db.Column(db.JSON)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, index=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (
        db.Index('ix_strike_rates_entity_lookup', 'type', 'jurisdiction', 'entity_id'),
        db.Index('ix_strike_rates_name_lookup', 'type', 'jurisdiction', 'normalised_name'),
    )

    def __repr__(self):
        return f'<StrikeRate {self.type} {self.name}>'


class Bet(db.Model):
    """James's personal bet log across all sports (admin-only Bet Tracker feature)"""
    __tablename__ = 'bets'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    date_placed = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    sport = db.Column(db.String(30), nullable=False, default='Horse Racing')
    event_track = db.Column(db.String(200))  # race/track/fixture/event name
    selection = db.Column(db.String(200), nullable=False)  # horse/team/fighter/player backed
    bookie = db.Column(db.String(50))
    stake = db.Column(db.Float, nullable=False)
    odds = db.Column(db.Float, nullable=False)
    result = db.Column(db.String(20), nullable=False, default='pending')  # pending/won/lost/refunded
    payout = db.Column(db.Float, default=0.0)
    notes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('bets', lazy=True, cascade='all, delete-orphan'))

    @property
    def profit(self):
        """Net profit/loss for this bet. Pending bets don't affect profit yet."""
        if self.result == 'won':
            return round((self.payout or 0.0) - self.stake, 2)
        if self.result == 'lost':
            return round(-self.stake, 2)
        return 0.0

    def __repr__(self):
        return f'<Bet {self.sport}: {self.selection} ({self.result})>'


class BudgetCategory(db.Model):
    """Budget Tracker fortnightly expense category. Shared between both accounts."""
    __tablename__ = 'budget_categories'

    id = db.Column(db.Integer, primary_key=True)
    group_name = db.Column(db.String(100), nullable=False)
    category_name = db.Column(db.String(100), nullable=False)
    default_allowance = db.Column(db.Float, nullable=False, default=0.0)
    sort_order = db.Column(db.Integer, nullable=False, default=0)
    is_debt_payment = db.Column(db.Boolean, default=False)  # feeds the debt_tracker payoff schedule

    def __repr__(self):
        return f'<BudgetCategory {self.group_name}/{self.category_name}>'


class BudgetFortnight(db.Model):
    """One row per fortnight period tracked in the Budget Tracker."""
    __tablename__ = 'budget_fortnights'

    id = db.Column(db.Integer, primary_key=True)
    fortnight_number = db.Column(db.Integer, unique=True, nullable=False)
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date, nullable=False)

    def __repr__(self):
        return f'<BudgetFortnight #{self.fortnight_number} {self.start_date}–{self.end_date}>'


class BudgetEntry(db.Model):
    """Actual spend logged against a category for a given fortnight. Shared data — not per-user."""
    __tablename__ = 'budget_entries'

    id = db.Column(db.Integer, primary_key=True)
    fortnight_id = db.Column(db.Integer, db.ForeignKey('budget_fortnights.id'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('budget_categories.id'), nullable=False)
    actual_spend = db.Column(db.Float, nullable=False, default=0.0)
    updated_by = db.Column(db.String(80))  # username of whoever last logged this entry
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    fortnight = db.relationship('BudgetFortnight', backref=db.backref('entries', lazy=True, cascade='all, delete-orphan'))
    category = db.relationship('BudgetCategory', backref=db.backref('entries', lazy=True, cascade='all, delete-orphan'))

    __table_args__ = (
        db.UniqueConstraint('fortnight_id', 'category_id', name='uq_budget_entry_fortnight_category'),
    )

    def __repr__(self):
        return f'<BudgetEntry fortnight={self.fortnight_id} category={self.category_id}: {self.actual_spend}>'


class DebtConfig(db.Model):
    """Editable assumptions for the credit card payoff tracker (single shared row)."""
    __tablename__ = 'debt_tracker_config'

    id = db.Column(db.Integer, primary_key=True)
    starting_balance = db.Column(db.Float, nullable=False, default=23000.0)
    annual_interest_rate = db.Column(db.Float, nullable=False, default=20.0)  # percent
    planned_fortnightly_payment = db.Column(db.Float, nullable=False, default=1455.14)
    updated_by = db.Column(db.String(80))
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class DebtTracker(db.Model):
    """Auto-generated credit card payoff schedule — one row per fortnight, recalculated on write."""
    __tablename__ = 'debt_tracker'

    id = db.Column(db.Integer, primary_key=True)
    fortnight_number = db.Column(db.Integer, unique=True, nullable=False)
    starting_balance = db.Column(db.Float, nullable=False)
    interest_rate = db.Column(db.Float, nullable=False)
    balance_start = db.Column(db.Float, nullable=False)
    interest = db.Column(db.Float, nullable=False)
    planned_payment = db.Column(db.Float, nullable=False)
    actual_paid = db.Column(db.Float, nullable=False)
    balance_end = db.Column(db.Float, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f'<DebtTracker #{self.fortnight_number}: {self.balance_start} -> {self.balance_end}>'


class ChatMessage(db.Model):
    """Chat messages between users and Claude AI assistant"""
    __tablename__ = 'chat_messages'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    role = db.Column(db.String(20), nullable=False)  # 'user' or 'assistant'
    content = db.Column(db.Text, nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    session_id = db.Column(db.String(50))
    
    user = db.relationship('User', backref='chat_messages')
    
    def __repr__(self):
        return f'<ChatMessage {self.role}: {self.content[:30]}...>'
